export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';
export const LOAD_CHOICE_FAIL = 'LOAD_CHOICE_FAIL';
export const LOAD_CHOICE_SUCCESS = 'LOAD_CHOICE_SUCCESS';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
export const BACK_TO_RESULTS = 'BACK_TO_RESULTS';
export const CHANGE_FILTER = 'CHANGE_FILTER';
export const SET_SEARCH_STRING = 'SET_SEARCH_STRING';
